{{- if .Values.vpn.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qbittorrent.fullname" . }}-vpn-config
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
type: Opaque
stringData:
  vpn.conf: |
    {{- .Values.vpn.configFile | nindent 4 }}
{{- end }}
