{{- if .Values.vpn.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qbittorrent.fullname" . }}-vpn-scripts
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
data:
  up.sh: |
    {{- .Values.vpn.scripts.up | nindent 4 }}
  down.sh: |
    {{- .Values.vpn.scripts.down | nindent 4 }}
{{- end }}
