{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ollama.fullname" . }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "ollama.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
---
{{- if and .Values.webui.enabled .Values.webui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ollama.fullname" . }}-webui
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
  {{- with .Values.webui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.webui.ingress.className }}
  ingressClassName: {{ .Values.webui.ingress.className }}
  {{- end }}
  {{- if .Values.webui.ingress.tls }}
  tls:
    {{- toYaml .Values.webui.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.webui.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "ollama.fullname" $ }}-webui
                port:
                  name: webui
          {{- end }}
    {{- end }}
{{- end }}
