apiVersion: v1
entries:
  flaresolverr:
  - apiVersion: v2
    appVersion: v3.3.21
    created: "2026-02-24T02:41:51.490471529Z"
    description: FlareSolverr - Proxy server to bypass Cloudflare protection
    digest: e2204fc002ec30ed1837333fc5e10c04ef2b0af124159b2358a480274947102b
    name: flaresolverr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/flaresolverr-1.0.0.tgz
    version: 1.0.0
  jackett:
  - apiVersion: v2
    appVersion: 0.24.1184
    created: "2026-02-24T02:41:51.490885893Z"
    description: Jackett torrent tracker proxy
    digest: d67cee1839b19bc0c4c080777c275efef99e24945f0de7627245bdaed0ad4caf
    name: jackett
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/jackett-1.0.0.tgz
    version: 1.0.0
  qbittorrent:
  - apiVersion: v2
    appVersion: 4.6.3
    created: "2026-02-24T02:41:51.491407517Z"
    description: qBittorrent torrent client
    digest: 34208a33a7f548cec0595b2bbfd517b51de41b7b29327949ab6d4cb7464027f9
    name: qbittorrent
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/qbittorrent-1.0.0.tgz
    version: 1.0.0
  radarr:
  - apiVersion: v2
    appVersion: 5.16.3.9541
    created: "2026-02-24T02:41:51.491748434Z"
    description: Radarr movie collection manager
    digest: 85418c1f4742bfccef2e6a85480aa8feeb6cf47ae10c8bfeab567541eb4be4dc
    name: radarr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/radarr-1.0.0.tgz
    version: 1.0.0
  sabnzbd:
  - apiVersion: v2
    appVersion: 4.5.5
    created: "2026-02-24T02:41:51.492095432Z"
    description: SABnzbd Usenet download client
    digest: 9a308db25036888c9f0caf1faddc709988ce15d78dee40d24f1ee287653f6af8
    name: sabnzbd
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/sabnzbd-1.0.0.tgz
    version: 1.0.0
  sonarr:
  - apiVersion: v2
    appVersion: 4.0.11.2680
    created: "2026-02-24T02:41:51.492411502Z"
    description: Sonarr TV series collection manager
    digest: a10b7182b924a08bf24a25b3d02ed3088d1f27d0696db509f71095c6edf3d5e1
    name: sonarr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/sonarr-1.0.0.tgz
    version: 1.0.0
generated: "2026-02-24T02:41:51.489935459Z"
