apiVersion: v1
entries:
  jackett:
  - apiVersion: v2
    appVersion: 0.24.1184
    created: "2026-02-23T20:36:15.740200413Z"
    description: Jackett torrent tracker proxy
    digest: 0d30199059200326d979c1db560c26912600005eacc295163055d14d37ecff1f
    name: jackett
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/jackett-1.0.0.tgz
    version: 1.0.0
  qbittorrent:
  - apiVersion: v2
    appVersion: 4.6.3
    created: "2026-02-23T20:36:15.7406117Z"
    description: qBittorrent torrent client
    digest: c47740c74df9e5daeceb10595f6713d707e14182fc7fd79f1d07fc53c3d73082
    name: qbittorrent
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/qbittorrent-1.0.0.tgz
    version: 1.0.0
  radarr:
  - apiVersion: v2
    appVersion: 5.16.3.9541
    created: "2026-02-23T20:36:15.74094927Z"
    description: Radarr movie collection manager
    digest: be658caf157d99849ea91507aa7fba085957401d26b5afc898f15172c3e18b15
    name: radarr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/radarr-1.0.0.tgz
    version: 1.0.0
  sabnzbd:
  - apiVersion: v2
    appVersion: 4.5.5
    created: "2026-02-23T20:36:15.741292019Z"
    description: SABnzbd Usenet download client
    digest: 73e62d1c3796ec42553cbf621952a8094ad5954a0d976a9e251de7e851d072ed
    name: sabnzbd
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/sabnzbd-1.0.0.tgz
    version: 1.0.0
  sonarr:
  - apiVersion: v2
    appVersion: 4.0.11.2680
    created: "2026-02-23T20:36:15.741596176Z"
    description: Sonarr TV series collection manager
    digest: 5a8d745eda689b716e7359a13c6ffcdb743bb073306d9cb48873dfb4127f2a9c
    name: sonarr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/sonarr-1.0.0.tgz
    version: 1.0.0
generated: "2026-02-23T20:36:15.739725187Z"
