apiVersion: v1
entries:
  jackett:
  - apiVersion: v2
    appVersion: 0.24.1184
    created: "2026-02-23T21:50:50.149081256Z"
    description: Jackett torrent tracker proxy
    digest: f09a06386ca55ff43df4422348a2748b966fb3254ac2747aefba51a01da29ef8
    name: jackett
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/jackett-1.0.0.tgz
    version: 1.0.0
  qbittorrent:
  - apiVersion: v2
    appVersion: 4.6.3
    created: "2026-02-23T21:50:50.149493699Z"
    description: qBittorrent torrent client
    digest: 2fc6736caeeb109eb16d33ae10a2aeeb0607ea67f5f07715d38738232b709d4b
    name: qbittorrent
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/qbittorrent-1.0.0.tgz
    version: 1.0.0
  radarr:
  - apiVersion: v2
    appVersion: 5.16.3.9541
    created: "2026-02-23T21:50:50.149825731Z"
    description: Radarr movie collection manager
    digest: f9e10f8eb715c3da20dbb541b50083ccd15116452ce61acd370958f8a3340188
    name: radarr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/radarr-1.0.0.tgz
    version: 1.0.0
  sabnzbd:
  - apiVersion: v2
    appVersion: 4.5.5
    created: "2026-02-23T21:50:50.150177209Z"
    description: SABnzbd Usenet download client
    digest: a61099764d00efe39e12c1fd46e85432b807b3a541b43b51faa10652bf00b4b2
    name: sabnzbd
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/sabnzbd-1.0.0.tgz
    version: 1.0.0
  sonarr:
  - apiVersion: v2
    appVersion: 4.0.11.2680
    created: "2026-02-23T21:50:50.150456703Z"
    description: Sonarr TV series collection manager
    digest: 6f95c52329b6ec270f1c998c07648baf22bda463fd102277e0a362ceeb84068a
    name: sonarr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/sonarr-1.0.0.tgz
    version: 1.0.0
generated: "2026-02-23T21:50:50.148587301Z"
