apiVersion: v1
entries:
  jackett:
  - apiVersion: v2
    appVersion: 0.24.1184
    created: "2026-02-23T20:52:32.369790476Z"
    description: Jackett torrent tracker proxy
    digest: 64ec36f538479d9f2e80c7bfd1e0dba03f898debcda77084b018ff10f7db4119
    name: jackett
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/jackett-1.0.0.tgz
    version: 1.0.0
  qbittorrent:
  - apiVersion: v2
    appVersion: 4.6.3
    created: "2026-02-23T20:52:32.370476035Z"
    description: qBittorrent torrent client
    digest: 7680b36ba21ca24fb4eaa32b8c213586d87e332edf35b949347b61ab40cbf1e1
    name: qbittorrent
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/qbittorrent-1.0.0.tgz
    version: 1.0.0
  radarr:
  - apiVersion: v2
    appVersion: 5.16.3.9541
    created: "2026-02-23T20:52:32.371034486Z"
    description: Radarr movie collection manager
    digest: 3c46ca4665155cadde3f07e89b7629bbe65e4b614ffe5765939aea1d32b41abb
    name: radarr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/radarr-1.0.0.tgz
    version: 1.0.0
  sabnzbd:
  - apiVersion: v2
    appVersion: 4.5.5
    created: "2026-02-23T20:52:32.371533427Z"
    description: SABnzbd Usenet download client
    digest: bbbc19a0a0922c7c267089684d102c23b8622951f5834e158130b92ec1e1c0a9
    name: sabnzbd
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/sabnzbd-1.0.0.tgz
    version: 1.0.0
  sonarr:
  - apiVersion: v2
    appVersion: 4.0.11.2680
    created: "2026-02-23T20:52:32.371834378Z"
    description: Sonarr TV series collection manager
    digest: 973a31a6b89d990b95bafebdcc41e2d3712036956cb30f41f8156835dbe8b8db
    name: sonarr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/sonarr-1.0.0.tgz
    version: 1.0.0
generated: "2026-02-23T20:52:32.369153969Z"
