apiVersion: v1
entries:
  jackett:
  - apiVersion: v2
    appVersion: 0.24.1184
    created: "2026-02-24T01:34:34.445523627Z"
    description: Jackett torrent tracker proxy
    digest: bc535079136129d82c7972b6690c6ee7d831f46c02e08cbc1ce6f840228c8b10
    name: jackett
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/jackett-1.0.0.tgz
    version: 1.0.0
  qbittorrent:
  - apiVersion: v2
    appVersion: 4.6.3
    created: "2026-02-24T01:34:34.445940415Z"
    description: qBittorrent torrent client
    digest: 93cc4a011130cdc29f6152c4c300bb222a8a47b37f9150bf96578180b4519a50
    name: qbittorrent
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/qbittorrent-1.0.0.tgz
    version: 1.0.0
  radarr:
  - apiVersion: v2
    appVersion: 5.16.3.9541
    created: "2026-02-24T01:34:34.446265072Z"
    description: Radarr movie collection manager
    digest: 25b91dce14944740266ef71cda272d082ae5f0960105cd0f5ae0765c3a6f194b
    name: radarr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/radarr-1.0.0.tgz
    version: 1.0.0
  sabnzbd:
  - apiVersion: v2
    appVersion: 4.5.5
    created: "2026-02-24T01:34:34.446573728Z"
    description: SABnzbd Usenet download client
    digest: 1295866db1cdb5eaf3c6a0888813b921b5664a9cfbfc30fda403e40b630343ec
    name: sabnzbd
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/sabnzbd-1.0.0.tgz
    version: 1.0.0
  sonarr:
  - apiVersion: v2
    appVersion: 4.0.11.2680
    created: "2026-02-24T01:34:34.446854342Z"
    description: Sonarr TV series collection manager
    digest: 05adc8a966cf2b25a7c0dad7fa50fbb130c93ef99e91a0d6559f4530a064a122
    name: sonarr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/sonarr-1.0.0.tgz
    version: 1.0.0
generated: "2026-02-24T01:34:34.445076212Z"
