apiVersion: v1
entries:
  jackett:
  - apiVersion: v2
    appVersion: 0.24.1184
    created: "2026-02-23T18:14:11.701359162Z"
    description: Jackett torrent tracker proxy
    digest: 6e899bb59f1e5ea9bfd429ba7b2c4cc1cc2c33bcbd325b1d1d29936b61a4820b
    name: jackett
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/jackett-1.0.0.tgz
    version: 1.0.0
  qbittorrent:
  - apiVersion: v2
    appVersion: 5.0.2
    created: "2026-02-23T18:14:11.701685991Z"
    description: qBittorrent torrent client
    digest: 527e0cd061f6a1c597143a6d4311f65772b0e7d16f5611f6640b350df33834eb
    name: qbittorrent
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/qbittorrent-1.0.0.tgz
    version: 1.0.0
  radarr:
  - apiVersion: v2
    appVersion: 5.16.3.9541
    created: "2026-02-23T18:14:11.702020846Z"
    description: Radarr movie collection manager
    digest: 4600ae81d9a2be6b9db03ef17798ee6222bb12d63e2cab1e04701d9abea9ad90
    name: radarr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/radarr-1.0.0.tgz
    version: 1.0.0
  sabnzbd:
  - apiVersion: v2
    appVersion: 4.5.5
    created: "2026-02-23T18:14:11.702321627Z"
    description: SABnzbd Usenet download client
    digest: fd7027d2e0440b8779e64a8cc5a6c2eea45727e7a7e9c91f11496e184a4dd640
    name: sabnzbd
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/sabnzbd-1.0.0.tgz
    version: 1.0.0
  sonarr:
  - apiVersion: v2
    appVersion: 4.0.11.2680
    created: "2026-02-23T18:14:11.702611538Z"
    description: Sonarr TV series collection manager
    digest: 68be433b60eb8b2a6261c211391ba384986af5f1b7800fbf12a6a2f50e52dd48
    name: sonarr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/sonarr-1.0.0.tgz
    version: 1.0.0
generated: "2026-02-23T18:14:11.700915284Z"
