apiVersion: v1
entries:
  flaresolverr:
  - apiVersion: v2
    appVersion: v3.3.21
    created: "2026-03-01T19:32:20.825726317Z"
    description: FlareSolverr - Proxy server to bypass Cloudflare protection
    digest: b64d9930605c254beb80f50c269908ec3ec74531b7ac4e3fcf9014d0c1a7225d
    name: flaresolverr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/flaresolverr-1.0.0.tgz
    version: 1.0.0
  github-runner:
  - apiVersion: v2
    appVersion: 2.332.0
    created: "2026-03-01T19:32:20.826018247Z"
    description: Self-hosted GitHub Actions runner
    digest: 549575caa0f09c5ba33030b0d576ec44256f1f84dbc8e390a9efea7239ac6723
    name: github-runner
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/github-runner-1.0.0.tgz
    version: 1.0.0
  jackett:
  - apiVersion: v2
    appVersion: 0.24.1184
    created: "2026-03-01T19:32:20.826329563Z"
    description: Jackett torrent tracker proxy
    digest: f4cf6eb965b92fdd77e0a6e59231762c8f21554169506a1681fc61661ba35fbe
    name: jackett
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/jackett-1.0.0.tgz
    version: 1.0.0
  qbittorrent:
  - apiVersion: v2
    appVersion: 4.6.3
    created: "2026-03-01T19:32:20.826738433Z"
    description: qBittorrent torrent client
    digest: 826273cd6a4358f4faf7e85ba59eebbd3cf99dd5b66305e515f31c875154c2c0
    name: qbittorrent
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/qbittorrent-1.0.0.tgz
    version: 1.0.0
  radarr:
  - apiVersion: v2
    appVersion: 5.16.3.9541
    created: "2026-03-01T19:32:20.827088973Z"
    description: Radarr movie collection manager
    digest: 308b6671279d206da91ba43383046dfd8bc9f7530a6ee7b50310f9cb978ebb31
    name: radarr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/radarr-1.0.0.tgz
    version: 1.0.0
  sabnzbd:
  - apiVersion: v2
    appVersion: 4.5.5
    created: "2026-03-01T19:32:20.827409637Z"
    description: SABnzbd Usenet download client
    digest: 116c973f1dd69feed6efc5d08e2fc74f2d2537e7b77828704323cf155d1798bf
    name: sabnzbd
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/sabnzbd-1.0.0.tgz
    version: 1.0.0
  sonarr:
  - apiVersion: v2
    appVersion: 4.0.11.2680
    created: "2026-03-01T19:32:20.827741993Z"
    description: Sonarr TV series collection manager
    digest: 07cc509f6a68cddee5491d8ee727d21728f3370094dc892e68ba7d83b600253d
    name: sonarr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/sonarr-1.0.0.tgz
    version: 1.0.0
generated: "2026-03-01T19:32:20.8253086Z"
