{{- if .Values.coordinator.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "llama-cpp.fullname" . }}
  labels:
    {{- include "llama-cpp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.coordinator.service.type }}
  ports:
    - port: {{ .Values.coordinator.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "llama-cpp.selectorLabels" . | nindent 4 }}
{{- end }}
