{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "qbittorrent.fullname" . }}-config
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
  {{- if .Values.persistence.config.skipUninstall }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.config.storageClass }}
  storageClassName: {{ .Values.persistence.config.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
{{- end }}
